// map contains unique value 
// const map = new Map()
// map.set('IN', "India")
// map.set('US', "United States")
// map.set('FR', "France")

// console.log(map);

// for (const [value,m] of map) {
//     console.log(m,value);
// }

// const myOb = {
//     In : "India",
//     US : "UNITED STATES",
//     FR : "France"
// }

// for (const [key , value] of myOb) {
//     console.log(key , value);    
// }

// for (const [key , value] of myOb) {
//     console.log(key , value);    
// }


const code = ["java" , "JS ", "html"];

// code.forEach( function (value) { 
//     console.log(value);// name ni dalte isme array ka 
// })

code.forEach( (value)=>{
    console.log(value);
} )